name: "Build and Deploy"
on: [push, workflow_dispatch]
env:
  AZURE_WEBAPP_NAME: github-secrets-action
  AZURE_WEBAPP_PACKAGE_NAME: "../published"
  NETCORE_VERSION: "3.1.101"
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up dotnet Core ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}
      - name: Restore
        run: |
          cd core-web-app
          dotnet restore
      - name: Build
        run: |
          cd core-web-app
          dotnet build --no-restore
      - name: Publish
        run: |
          cd core-web-app
          dotnet publish --configuration Release --output ${{ env.AZURE_WEBAPP_PACKAGE_NAME }}
  - name: Azure Pipelines Action
  uses: Azure/pipelines@v1
  with:
    azure-devops-project-url: 'https://dev.azure.com/DevopsCPTTraining/EngageDemo'
    azure-pipeline-name: 'Github-Actions-CD' # name of the Azure pipeline to be triggered
    azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
