name: Removal of Old branches

on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./.github/scripts/build.sh
         ./.github/scripts/build.sh
      shell: bash
