name: Delete abandoned branches

on: [push]
jobs:
  cleanup-old-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: cultureamp/delete-old-branches-action@v0.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          min-num-branches: 20
          days-to-keep-branches: 14
