name: Removal of Old branches

on: [push]
jobs:
  removal-of-old-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: ./.github/scripts/build.sh
        shell: bash
