name: Removal of Old branches

on: [push]
jobs:
  removal-of-old-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: ./home/runner/work/core-web-app/core-web-app/.github/scripts/build.sh
        shell: bash
